### ISSUE TITLE
Json-to-Go to generate swagger model

### ISSUE THREAD

**Issue by yanpozka** [emicklei/swagger2#1]
Hi @emicklei this repo is what I'm looking for, after fix this tool:
http://mholt.github.io/json-to-go/   https://github.com/mholt/json-to-go

I think that generate a model for Swagger 2 will be more easy with json-to-go, it'll be just create a generic json for each field of a swagger doc, I can help you if you agree with my idea

**Comment by emicklei** [comment]
Thank you for sharing this idea.

I think handcrafting the structs is not much work (actually a lot has been done already) and gives the required control about mapping fields to names (e.g. the ordered maps).
